### ISSUE TITLE
'Cannot mount mountpoint or dataset is busy'

### ISSUE THREAD

**Issue by ChenHuge** [gordan-bobic/zfs-fuse#14]
Hello, this is Chen.
I get a problem when I use the zfs-fuse.
zfs-fuse will mount error 'Cannot mount mountpoint or dataset is busy' in the this case.

dd if=/dev/zero of=/vm_img/backup.img bs=1G count=0 seek=256
zpool create /vm_img/backup.img vm_backup..
zfs set mountpoint=/vm_backup vm_backup
zfs create vm_backup/win2008R2
zfs set compression=on vm_backup/win2008R2

dd if=/dev/zero of=/db_img/backup.img bs=1G count=0 seek=256
zpool create /db_img/backup.img db_backup
zfs set mountpoint=/db_backup db_backup
zfs create db_backup/oracle
zfs set compression=on db_backup/oracle

When VM win2008R2 is syncing to /vm_backup/win2008R2 with tool rsync, I mount db_backup/oracle(zfs mount db_backup/oracle), sometimes, zfs-fuse will return error 'Cannot mount mountpoint or dataset is busy'. 
I debug the code, the error is from file 'dsl_dataset.c' line '744: if (ds->ds_owner == NULL &&', because ‘ds->ds_owner’ is not NULL. I don't know why this happens.

Could anyone help me? Thank you very much.

**Comment by gordan-bobic** [comment]
Sounds like a bug. I'll have to check against the ZoL and Illumos repositories to see if the code is dissimilar.

Just out of interest, why was db_backup/oracle not mounted automatically as soon as you imported the db_backup pool? Do you have better results if you use mount -t zfs db_backup/oracle /db_backup/oracle?

What OS are you using? Are you using the latest zfs-fuse from this repository?

**Comment by ChenHuge** [comment]
Thank you for your attention!
1. Why was db_backup/oracle not mounted automatically as soon as you imported the db_backup pool? 
   In my case, the zfs will just be mounted when I need to backup the VMs and DBs, other times the zpools are unmounted.
2. Do you have better results if you use mount -t zfs db_backup/oracle /db_backup/oracle?
   Yes, I did it, when zfs mount return error 'Cannot mount mountpoint or dataset is busy', mount -t zfs db_backup/oracle /db_backup/oracle will also return 'Cannot mount mountpoint or dataset is busy'.
3. What OS are you using?
   CentOS6.5_x64
4. Are you using the latest zfs-fuse from this repository?
   I use version 0.7.2. 

Thank  you very much.

**Comment by gordan-bobic** [comment]
Right, but if the mountpoint is set, doing "zpool import db_backup" it will auto-mount it.

I don't think you could ever unmount/mount a FS using zfs-fuse. What you _can_ do is set mountpoint=legacy to unmount it, and then use "mount -t zfs" to mount it and "umount" to unmount it.

Just out of interest, is there a good reason why you cannot use ZoL instead of zfs-fuse on that system? ZoL works well on CentOS 6 x64.
