### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by rlee3030** [gordan-bobic/zfs-fuse#16]
I tried to build this on Centos 6.8 but getting this error below.

gcc -o cmd/mount_zfs/mount_zfs.o -c -pipe -Wall -std=c99 -Wno-switch - Wno-unused -Wno-missing-braces -Wno-parentheses -Wno-uninitialized -Wcast-align -fno-strict-aliasing -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DTEXT_DOMAIN=\"zfs-fuse\" -02 -Wp, -D_FORTIFY_SOURCE=2 -fstack-protector -fstrict-volatile-bitfields --param=ssp-buffer-size=4 -s -)2 -DNDEBUG -fPIC -DLINUX_AIO -Ilib/libuutil/include -Ilib/libnvpair/include -Ilib/libumem/include -Ilib/libzfscommon/include -Ilib/libzpool/include -Ilib/libzfs/include -Ilib/libsolcompat/include -Ilib/libavl/include cmd/mount zfs/mount zfs.c
cc1: error: unrecognized command line option "-fstrict-volatile-bitfields"
scons: **\* [cmd/mount_zfs/mount_zfs.o] Error 1
scons: building terminated because of errors

getconf GNU_LIBPTHREAD_VERSION:  NPTL 2.12
gcc --version:   gcc (GCC) 4.4.7 20120313 (Red hat 4.4.7-17)

**Comment by gordan-bobic** [comment]
You'll have to back out commit https://github.com/gordan-bobic/zfs-fuse/commit/66657036a19a922693337c5f7023dbde7f4d75bb to build it with the compiler that ships with EL6.
