### ISSUE TITLE
zfs-fuse fails to build in Fedora with gcc8

### ISSUE THREAD

**Issue by rosset** [gordan-bobic/zfs-fuse#18]
Full Logs: https://kojipkgs.fedoraproject.org//work/tasks/7181/24917181/build.log

**Comment by gordan-bobic** [comment]
It sounds like you need to include:

```
BuildRequires: glibc-headers
```

in the spec file for that Fedora/gcc combination.

It's possible this used to be a part of @buildsys-build dependencies, but may have been removed in Fedora for whatever reason. Something to ask Fedora maintainers.

**Comment by rosset** [comment]
packages are here, but failure persists:

rpm -q glibc glibc-headers
glibc-2.26.9000-51.fc28.x86_64
glibc-headers-2.26.9000-51.fc28.x86_64

rpm -q gcc
gcc-8.0.1-0.9.fc28.x86_64

maybe it's due glibc-2.27 (2.26.9000 is a pre-release for 2.27)
http://lists.gnu.org/archive/html/info-gnu/2018-02/msg00000.html

**Comment by gordan-bobic** [comment]
Can you verify that whatever package provides /usr/include/rpc/types.h is installed? The fatal error is that it can't find the header, so whatever provides that header file needs to be installed. What do you get from

```
yum provides "*/rpc/types.h"
```

?

**Comment by rosset** [comment]
it's due https://fedoraproject.org/wiki/Changes/SunRPCRemoval but I'm not sure the best way to fix for now.

**Comment by gordan-bobic** [comment]
Sounds like a Fedora problem rather than zfs-fuse.
