### ISSUE TITLE
zfs-fuse.init missing from src.rpm

### ISSUE THREAD

**Issue by ElCoyote27** [gordan-bobic/zfs-fuse#5]
Hi Gordan,
Thanks for the great work. :)
Trying to rebuild http://ftp.redsleeve.org/pub/el7-devel/el7-extra/SRPMS/zfs-fuse-0.7.1-4.el7.src.rpm on RHEL6 fails because zfs-fuse.init is missing from the src.rpm:

scons: done building targets.
- /usr/bin/install -Dp -m 0755 /usr/src/redhat/SOURCES/zfs-fuse.init /usr/src/redhat/BUILDROOT/zfs-fuse-0.7.1-4.el6.x86_64/etc/rc.d/init.d/zfs-fuse
  /usr/bin/install: cannot stat `/usr/src/redhat/SOURCES/zfs-fuse.init': No such file or directory
  error: Bad exit status from /var/tmp/rpm-tmp.mh2qrc (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.mh2qrc (%install)

And this file isn't provided in the src.rpm.

In think this should be included unconditionally in the spec file otherwise it won't make it into the src.rpm (unless you have a different src.rpm for el6<).
Regards,
Vincent

**Comment by gordan-bobic** [comment]
Ah, that would be because EL7 uses systemd so it doesn't include the init script.
Try this:
http://ftp.redsleeve.org/pub/el6/packages/extra/SRPMS/zfs-fuse-0.7.1-1.el6.src.rpm

**Comment by ElCoyote27** [comment]
This fix makes it work for both (unprotect the source for el6< and shift the source numbers by one)

diff /usr/src/redhat/SPECS/zfs-fuse.spec.orig /usr/src/redhat/SPECS/zfs-fuse.spec
11d10
< %if %{?rhel} <= 6
13,19c12,16
< %else
< Source01:             zfs-fuse.service
< %endif
< Source02:             zfs-fuse.scrub
< Source03:             zfs-fuse.sysconfig
< Source04:             zfs-fuse.zfsrc

## < Source05:             zfs-fuse.modules-load

> Source02:             zfs-fuse.service
> Source03:             zfs-fuse.scrub
> Source04:             zfs-fuse.sysconfig
> Source05:             zfs-fuse.zfsrc
> Source06:             zfs-fuse.modules-load
> 66c63
> 
> ## < %{__install} -Dp -m 0644 %{SOURCE1} %{buildroot}%{_unitdir}/%{name}.service
> 
> %{__install} -Dp -m 0644 %{SOURCE2} %{buildroot}%{_unitdir}/%{name}.service
> 68,72c65,69
> < %{__install} -Dp -m 0755 %{SOURCE2} %{buildroot}%{_sysconfdir}/cron.weekly/98-%{name}-scrub
> < %{__install} -Dp -m 0644 %{SOURCE3} %{buildroot}%{_sysconfdir}/sysconfig/%{name}
> < %{__install} -Dp -m 0644 %{SOURCE4} %{buildroot}%{_sysconfdir}/zfs/zfsrc
> < %{__install} -Dp -m 0644 %{SOURCE5} %{buildroot}%{_sysconfdir}/modules-load.d/fuse.conf
> 
> ## < %{__install} -Dp -m 0644 %{SOURCE5} %{buildroot}%{_sharedstatedir}/modules-load.d/fuse.conf
> 
> %{__install} -Dp -m 0755 %{SOURCE3} %{buildroot}%{_sysconfdir}/cron.weekly/98-%{name}-scrub
> %{__install} -Dp -m 0644 %{SOURCE4} %{buildroot}%{_sysconfdir}/sysconfig/%{name}
> %{__install} -Dp -m 0644 %{SOURCE5} %{buildroot}%{_sysconfdir}/zfs/zfsrc
> %{__install} -Dp -m 0644 %{SOURCE6} %{buildroot}%{_sysconfdir}/modules-load.d/fuse.conf
> %{__install} -Dp -m 0644 %{SOURCE7} %{buildroot}%{_sharedstatedir}/modules-load.d/fuse.conf

**Comment by ElCoyote27** [comment]
The reason why I went with the el7 source is that the two rpms seemed somwhat different with -4 being an improvement..

[raistlin@daltigoth tmp]$ rpm -qlp zfs-fuse-0.7.1-1.el6.src.rpm 
zfs-fuse-0.7.1.tar.xz
zfs-fuse.init
zfs-fuse.scrub
zfs-fuse.spec
zfs-fuse.sysconfig
[raistlin@daltigoth tmp]$ rpm -qlp zfs-fuse-0.7.1-4.el7.src.rpm 
zfs-fuse-0.7.1.tar.xz
zfs-fuse.modules-load  <================
zfs-fuse.scrub
zfs-fuse.service
zfs-fuse.spec
zfs-fuse.sysconfig
zfs-fuse.zfsrc   <================

**Comment by gordan-bobic** [comment]
Have you tried using the spec file in git? You may have to adjust the version number, but I think that should cover both cases.

The -4 tweaks are specific to systemd distributions.

**Comment by ElCoyote27** [comment]
I don't think the spec file in git covers both cases.. (tried both master and pool28):

[raistlin@daltigoth zfs-fuse]$ git status zfs-fuse.spec 

# On branch pool28

nothing to commit (working directory clean)
[raistlin@daltigoth zfs-fuse]$ diff zfs-fuse.spec /usr/src/redhat/SPECS/zfs-fuse.spec.orig 

(zfs-fuse.orig is the one from el7 src.rpm).
Would you want a pull request for these changes?
Vincent

**Comment by gordan-bobic** [comment]
If you look here:
https://github.com/gordan-bobic/zfs-fuse/blob/pool28/zfs-fuse.spec

That spec file includes both the systemd service and the sysv style init script, and it rolls the appropriate one into the binary depending on whether you are building it on el6 or el7.

**Comment by ElCoyote27** [comment]
Just a small comment:
I think the two rhel defines at the top should be:
%if 0%{?rhel} <= 6
Instead of:
%if %{?rhel} <= 6
(this breaks on el5).
Thanks,
